### ISSUE TITLE
convert_weight.py运行不成功 

### ISSUE THREAD

**Issue by zly19540609** [Byronnar/tensorflow-serving-yolov3#109]
我想运行convert_weight.py 把608改为416，出现下面错误

Traceback (most recent call last):
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\framework\ops.py", line 1626, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be evenly divisible by 2527 but is 56784 for 'pred_multi_scale/Reshape' (op: 'Reshape') with input shapes: [1,52,52,3,7], [4] and with input tensors computed as partial shapes: input[1] = [?,19,19,7].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\zly\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\zly\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\zly\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\CodeRepository\tensorflow_serving_yolov3\convert_weight.py", line 41, in <module>
    model = YOLOV3(input_data, training)
  File "e:\CodeRepository\tensorflow_serving_yolov3\core\yolov3.py", line 48, in __init__
    self.pred_multi_scale = tf.concat([tf.reshape(self.pred_sbbox, [-1, 19, 19, 7]),
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7546, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\framework\ops.py", line 1790, in __init__
    control_input_ops)
  File "C:\Users\zly\.conda\envs\yolov3-tf1\lib\site-packages\tensorflow\python\framework\ops.py", line 1629, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension size must be evenly divisible by 2527 but is 56784 for 'pred_multi_scale/Reshape' (op: 'Reshape') with input shapes: [1,52,52,3,7], [4] and with input tensors computed as partial shapes: input[1] 
= [?,19,19,7].

**Comment by santiago2389** [comment]
Is this issue solved? I am also facing the same issue.

**Comment by zly19540609** [comment]
I can't solve it. So I use 416 size  train again. Then use convert_weight.py
